package/yq: disable CGO to fix cross-compilation failures
runtime.cgo_yield: relocation target _cgo_yield not defined
net._cgo_77133bf98b3a_C2func_getaddrinfo: relocation target _cgo_77133bf98b3a_C2func_getaddrinfo not defined
net._cgo_77133bf98b3a_Cfunc_freeaddrinfo: relocation target _cgo_77133bf98b3a_Cfunc_freeaddrinfo not defined
net._cgo_77133bf98b3a_Cfunc_gai_strerror: relocation target _cgo_77133bf98b3a_Cfunc_gai_strerror not defined
/home/thomas/Documents/external/buildroot/output/host/lib/go/pkg/tool/linux_amd64/link: too many errors

The errors occur because yq doesn't actually require CGO - it's a pure Go
application with no C dependencies. However, the Go toolchain was attempting
to use CGO during cross-compilation, leading to unresolved symbols.

So disable CGO, which is confirmed by upstream's build configuration that
explicitly sets CGO_ENABLED=0 in their .goreleaser.yaml:

https://github.com/mikefarah/yq/blob/v4.49.2/.goreleaser.yaml#L14

Fixes:
 - https://autobuild.buildroot.org/results/52ec88fdcfea00f32a4dffea5cebb901ecdbd1ad

Signed-off-by: Thomas Devoogdt <thomas@devoogdt.com>