package/libgtk4: fix compile error if cairo zlib is not enabled
This commit adds some patches to avoid the need for cairo zlib.
Otherwise, this error occurs at build time:

../gtk/gtkprintoperation.c:26:10: fatal error: cairo-pdf.h: No such file or directory

Note that libpng has to be selected since cairo only selects it if zlib support is enabled.

Upstream issue: https://gitlab.gnome.org/GNOME/gtk/-/issues/5072.
Upstream fix: https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/7717.

These patches have been needed since the introduction of libgtk4,
libgtk3 was a bit different since buildroot selected the required
cairo-{ps,pdf,svg} since the introduction of that package.

Signed-off-by: Thomas Devoogdt <thomas@devoogdt.com>